# Usar la imagen base de Tomcat
FROM tomcat:latest

# Copiar el contenido de la aplicación web al directorio webapps/ROOT de Tomcat
COPY ./webapps/ROOT /usr/local/tomcat/webapps/ROOT

# Exponer el puerto 8080
EXPOSE 8080